#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
# shellcheck source=scripts/common.sh
source "$SCRIPT_DIR/common.sh"

ROOTFS_DIR="${ROOTFS_DIR:-$PROJECT_ROOT/build/rootfs}"
CLIENT_CIDR="${CLIENT_CIDR:-192.168.76.0/24}"
NFS_OPTIONS="${NFS_OPTIONS:-rw,sync,no_subtree_check,no_root_squash,insecure}"
EXPORT_FILE="${EXPORT_FILE:-/etc/exports.d/karudeb.exports}"

ROOTFS_DIR="$(abs_path "$ROOTFS_DIR")"

[[ -d "$ROOTFS_DIR" ]] || die "rootfs directory not found: $ROOTFS_DIR"
need_cmd exportfs nfs-kernel-server
need_cmd rpcbind rpcbind

rootfs_uid="$(stat -c %u "$ROOTFS_DIR")"
if [[ "$rootfs_uid" != "0" && "${ALLOW_SHIFTED_NFS:-0}" != "1" ]]; then
  die "rootfs is host-owned by uid $rootfs_uid, not root. Extract a packaged rootfs as root or rebuild with MMDEBSTRAP_USE_SUDO=1; set ALLOW_SHIFTED_NFS=1 only if you really want to export shifted ownership"
fi

tmp="$(mktemp)"
{
  printf '# Generated by karudeb/scripts/export-nfs-root.sh\n'
  printf '%s %s(%s)\n' "$ROOTFS_DIR" "$CLIENT_CIDR" "$NFS_OPTIONS"
} >"$tmp"

as_root install -D -m 0644 "$tmp" "$EXPORT_FILE"
rm -f "$tmp"

if have_cmd systemctl; then
  as_root systemctl restart rpcbind || true
  as_root systemctl restart nfs-server || as_root systemctl restart nfs-kernel-server || true
fi

as_root exportfs -ra

info "Exported $ROOTFS_DIR to $CLIENT_CIDR"
as_root exportfs -v | sed -n "\#^$ROOTFS_DIR[[:space:]]#p"
